/*------------------------------------------------------------------------------
<auto-generated>
     This code was generated by a tool.
	    Code originates from EA Uml ClassTemplate.t4
     Changes to this file will be lost if the code is regenerated.
	    Code Generated Date: 	06 May 2017
	    ProjectModel: 			MedicsAway
	    Requested Namespace:	Model$1. Presentation Model$LayrCake$LayrCake$Models$Implementation
</auto-generated>
------------------------------------------------------------------------------*/
import { ModuleWithProviders } from '@angular/core';
import { Routes } from '@angular/router';

export interface IAspNetUser {
	id: number,
	email: string;
	emailConfirmed: boolean;
	passwordHash: string;
	securityStamp: string;
	phoneNumber: string;
	phoneNumberConfirmed: boolean;
	twoFactorEnabled: boolean;
	lockoutEndDateUtc?: Date;
	lockoutEnabled: boolean;
	accessFailedCount: number;
	userName: string;
	userID: string;
}

export interface ICompany {
	id: number,
	companyName: string;
	alias: string;
}

export interface IDDDAttribute {
	id: number,
	name: string;
	type: string;
	dDDElementRef?: number;
	dDDElement: IDDDElement;
}

export interface IDDDElement {
	id: number,
	name: string;
	parentDDDElementRef?: number;
	dDDPackageRef?: number;
	dDDFileRef?: number;
	dDDAttributes?: IDDDAttribute[];
	dDDPackage: IDDDPackage;
	dDDMethods?: IDDDMethod[];
	dDDProperties?: IDDDProperty[];
}

export interface IDDDLayer {
	id: number,
	name: string;
	description: string;
	dDDSolutionRef?: number;
	dDDLayerTemplateRef?: number;
	dDDSolution: IDDDSolution;
	dDDPackages?: IDDDPackage[];
}

export interface IDDDLayerTemplate {
	id: number,
	templateName: string;
	templateType: string;
	positionOnStack?: number;
}

export interface IDDDMethod {
	id: number,
	returnType: string;
	name: string;
	returnIsArray: boolean;
	dDDElementRef?: number;
	dDDElement: IDDDElement;
}

export interface IDDDPackage {
	id: number,
	name: string;
	dDDLayerRef?: number;
	parentDVPackageRef?: number;
	dDDElements?: IDDDElement[];
	dDDLayer: IDDDLayer;
	dDDPackageToPackageLinks?: IDDDPackageToPackageLink[];
	dDDSolutionToPackageLinks?: IDDDSolutionToPackageLink[];
}

export interface IDDDPackageToPackageLink {
	id: number,
	description: string;
	dDDPackageRef?: number;
	dDDProjectRef?: number;
	parentChildRelationship: string;
	dDDPackage: IDDDPackage;
	dDDProject: IDDDProject;
}

export interface IDDDProject {
	id: number,
	projectName: string;
	shortDescription: string;
	dDDPackageToPackageLinks?: IDDDPackageToPackageLink[];
}

export interface IDDDProperty {
	id: number,
	name: string;
	dDDElementRef?: number;
	dDDElement: IDDDElement;
}

export interface IDDDSolution {
	id: number,
	name: string;
	alias: string;
	sourceSafeUrl: string;
	dDDLayers?: IDDDLayer[];
	dDDSolutionToPackageLinks?: IDDDSolutionToPackageLink[];
	problemDomainSolutionLinks?: IProblemDomainSolutionLink[];
}

export interface IDDDSolutionToPackageLink {
	id: number,
	description: string;
	dDDSolutionRef?: number;
	dDDPackageRef?: number;
	isMasterSolution?: boolean;
	dDDPackage: IDDDPackage;
	dDDSolution: IDDDSolution;
}

export interface IMerchantProblemDomainLink {
	id: number,
	description: string;
	companyMerchantLinkRef?: number;
	problemDomainRef?: number;
	problemDomain: IProblemDomain;
}

export interface IProblemDomain {
	id: number,
	name: string;
	shortDesciption: string;
	merchantProblemDomainLinks?: IMerchantProblemDomainLink[];
	problemDomainSolutionLinks?: IProblemDomainSolutionLink[];
}

export interface IProblemDomainSolutionLink {
	id: number,
	description: string;
	problemDomainRef?: number;
	dDDSolutionRef?: number;
	dDDSolution: IDDDSolution;
	problemDomain: IProblemDomain;
}

export interface IProfile {
	id: number,
	profileImage_Ref?: number;
	photoGallery_Ref?: number;
	documentGallery_Ref?: number;
	personStatement_Blob_Ref?: number;
	factList_Ref?: number;
}

export interface IUser {
	id: number,
	lastAccessDateTime: Date;
	userRegistrationID?: number;
	registrationGUID: string;
	loginName: string;
	displayName: string;
	password: string;
	emailAddress: string;
	displaySystemErrors?: number;
	securityQuestion1ID: number;
	securityQuestion2ID: number;
	securityAnswer1: string;
	securityAnswer2: string;
	passKey?: number;
	deactivated?: Date;
	deactivatedBy?: number;
	unLocked?: Date;
	unLockedBy?: number;
}

export interface IPagedResults<T> {
     totalRecords: number;
     results: T;
}
